import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import Footer from "components/Footer/Footer";
import Header from "components/Header/Header";
import "./globals.css";
import { AuthProvider } from "contexts/auth";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Artopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className} bg-[#121212] text-white relative`}>
        <AuthProvider>
          <Header />
          {children}
          {/* <Footer /> */}
        </AuthProvider>
      </body>
    </html>
  );
}
